package config

import "golang.org/x/crypto/ssh"

const CFGPATH string = "~/.mysshw.toml"

// DefaultConfig 包含默认配置的字符串
const DefaultConfig = `# config example.
# see URL: https://github.com/cnphpbb/mysshw/blob/master/readme.md#config
cfg_dir = "./.mysshw.toml"   # default:  $HOME/.mysshw.toml

[sync]
type = "scp" # type: ( scp || github || gitee || Api-http || rpc ) default: scp
remote_uri = "127.0.0.1:22"
username = "root"
password = "$ZK7M@~1RY"
keyPath = ""
passphrase = ""
remote_path = "/data/backup/mysshw/mysshw.toml" # remote file path
access_token = "" # gitee_access_token
gist_id = ""  # gist_id

# config example.
# see URL: https://github.com/cnphpbb/mysshw/blob/master/readme.md#config
[[nodes]]
groups = "Groups01"
ssh = [
    # 
	# { name="no ssh conf", alias="", host="192.168.10.60", user="vm00", port=22, password="qwe123!@#qwe", keypath="~/.ssh/id_rsa", passphrase="abcdefghijklmn" },
    { name="vm-test", alias="TestNode", host="127.0.0.1", user="root", port=22, password="test#Password" },
]`

type (
	Configs struct {
		CfgDir  string   `toml:"cfg_dir" mapstructure:"cfg_dir"`
		SyncCfg SyncInfo `toml:"sync" mapstructure:"sync"`
		Nodes   []Nodes  `toml:"nodes" mapstructure:"nodes"`
	}

	SyncInfo struct {
		Type        string `toml:"type" mapstructure:"type"`
		RemoteUri   string `toml:"remote_uri" mapstructure:"remote_uri"`
		UserName    string `toml:"username" mapstructure:"username"`
		Password    string `toml:"password" mapstructure:"password"`
		KeyPath     string `toml:"keyPath" mapstructure:"keyPath"`
		Passphrase  string `toml:"passphrase" mapstructure:"passphrase"`
		RemotePath  string `toml:"remote_path" mapstructure:"remote_path"`
		AccessToken string `toml:"access_token" mapstructure:"access_token"`
		GistID      string `toml:"gist_id" mapstructure:"gist_id"`
	}
	Nodes struct {
		Groups   string     `toml:"groups"`
		SSHNodes []*SSHNode `toml:"ssh" mapstructure:"ssh"`
	}
	SSHNode struct {
		Name       string `toml:"name" mapstructure:"name"`
		Alias      string `toml:"alias,omitempty" mapstructure:"alias"`
		Host       string `toml:"host" mapstructure:"host"`
		User       string `toml:"user,omitempty" mapstructure:"user"`
		Port       int    `toml:"port,omitempty" mapstructure:"port"`
		KeyPath    string `toml:"keypath,omitempty" mapstructure:"keypath"`
		Passphrase string `toml:"passphrase,omitempty" mapstructure:"passphrase"`
		Password   string `toml:"password,omitempty" mapstructure:"password"`
	}
)

//type AutoGenerated struct {
//	CfgDir string `toml:"cfg_dir"`
//	Sync   struct {
//		Type        string `toml:"type"`
//		RemoteURI   string `toml:"remote_uri"`
//		Username    string `toml:"username"`
//		Password    string `toml:"password"`
//		KeyPath     string `toml:"keyPath"`
//		Passphrase  string `toml:"passphrase"`
//		RemotePath  string `toml:"remote_path"`
//		AccessToken string `toml:"access_token"`
//		GistID      string `toml:"gist_id"`
//	} `toml:"sync"`
//	Nodes []struct {
//		Groups string `toml:"groups"`
//		SSH    []struct {
//			Name       string `toml:"name"`
//			User       string `toml:"user,omitempty"`
//			Host       string `toml:"host"`
//			Port       int    `toml:"port,omitempty"`
//			Keypath    string `toml:"keypath,omitempty"`
//			Passphrase string `toml:"passphrase,omitempty"`
//			Password   string `toml:"password,omitempty"`
//			Alias      string `toml:"alias,omitempty"`
//		} `toml:"ssh"`
//	} `toml:"nodes"`
//}

func (n *SSHNode) SetUser() string {
	if n.User == "" {
		return "root"
	}
	return n.User
}

func (n *SSHNode) SetPort() int {
	if n.Port <= 0 {
		return 22
	}
	return n.Port
}

func (n *SSHNode) SetKeyPath() string {
	if n.KeyPath == "" {
		return ""
	}
	return n.KeyPath
}

func (n *SSHNode) SetPassword() ssh.AuthMethod {
	if n.Password == "" {
		return nil
	}
	return ssh.Password(n.Password)
}
